language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt

script: py.test -v --cov-report=term-missing --cov=aiohttp_auth --cov=tests tests
